#!/bin/bash
#$ -t 2-1077
#$ -S /bin/bash
#$ -V
#$ -l h_vmem=3G
#$ -wd /data2/home/ameert/regen_galfit/
#$ -o /data2/scratch/ameert/CMASS/i/job_output/
#$ -e /data2/scratch/ameert/CMASS/i/job_output/
#$ -N fis
#$ -tc 100
#$ -q all.q
#$ -l h="node01|node02|node03|node04|node05|node06|node07|node08|node09|node10|node11|node12|node13|node14|node15|node16|node17|node18|node19|node20|node21|node22"
# -hold_jid 571059

/data2/home/ameert/regen_galfit/measure_flag_no_regen.py $SGE_TASK_ID ser i


