#!/bin/bash
#$ -t 1-1076
#$ -S /bin/bash
#$ -V
#$ -l h_vmem=2G
#$ -wd /data2/scratch/ameert/CMASS/i/fits/ser
#$ -o /data2/scratch/ameert/CMASS/i/job_output/
#$ -e /data2/scratch/ameert/CMASS/i/job_output/
#$ -N hrs
#$ -l low
#$ -tc 80
# -hold_jid 559392
/data2/home/ameert/git_projects/astro_image_processing/folio_scripts/grid_scripts/clean_dir.py $SGE_TASK_ID
