import pylab as pl
import numpy as np
from astro_image_processing.MatplotRc import *

bins = {'mag':np.arange(14.0, 18.1, .5),
        'absmag':np.arange(-24.0, -15.99, .5), 'rad':np.arange(0.0, 12.1, 1.0),
        'n':np.arange(0.0, 8.01, 1.0), 'BT':np.arange(0.0, 1.01, .1),
        'pa':np.arange(0.0, 360.01, 30.0), 'ba':np.arange(0.0, 1.01, .1),
        'rbulgerdisk': np.arange(0.0, 1.51, 0.1),'sky':np.arange(-2.0, 2.01, .2)}
        
bins_num = { 'mag':{'mag':(45,30),'rad':(45,30),'n': (45,30),
                    'BT':(45,30),'rbulgerdisk':(45,30),'pa':(45,30),
                    'ba':(45,30),'sky':(45,30)},
             'absmag':{'mag':(45,30),'absmag':(45,30),
                       'rad':(45,30),'n': (45,30),
                    'BT':(45,30),'rbulgerdisk':(45,30),'pa':(45,30),
                    'ba':(45,30),'sky':(45,30)},
             'rad':{'rad':(45,30),'n': (45,30),'sky':(45,30)},
             'n':{'n':(45,30)},
             'BT':{'mag':(45,30),'rad':(45,30),
                   'BT':(45,30),'n':(45,30),'sky':(45,30)},
             'pa':{'pa':(45,30)},
             'ba':{'ba':(45,30)},
             'rbulgerdisk':{'rbulgerdisk':(45,30)},
             'sky':{'mag':(45,30),'abmag':(45,30),'rad':(45,30),'n': (45,30),
                    'BT':(45,30),'rbulgerdisk':(45,30)}}

bin_max = { 'mag':{'mag':5.0,'rad':1.5,'n': 1.0,
                    'BT':5.0,'rbulgerdisk':5.0,'ba':5.0,'pa':5.0 ,'sky':5.0 },
            'absmag':{'mag':5.0,'absmag':5.0,'rad':1.5,'n': 1.0,
                    'BT':5.0,'rbulgerdisk':5.0,'ba':5.0,'pa':5.0,'sky':5.0 },
             'rad':{'rad':0.75,'n': 1.0,'sky':5.0 },
             'n':{'n':0.5},
             'BT':{'mag':5.0,'rad':1.5,'BT':12.0,'n':0.5,'sky':5.0 },
             'pa':{'pa':12.0},
             'ba':{'ba':12.0},
             'rbulgerdisk':{'rbulgerdisk':5.0},
            'sky':{'mag':5.0,'absmag':5.0,'rad':1.5,'n': 1.0,
                    'BT':5.0,'rbulgerdisk':5.0,'ba':5.0,'pa':5.0 }}

bin_lims = {'sky':{'mag':(-2.0,2.0),'absmag':(-2.0,2.0),
                   'rad':(-1.0,1.0),'n': (-8.0,8.0),
                    'BT':(-1.0,1.0),'rbulgerdisk':(-2.0,2.0)},
            'mag':{'mag':(-2.0,2.0),'rad':(-1.0,0.75),'n': (-8.0,8.0),
                    'BT':(-1.0,1.0),'rbulgerdisk':(-10.0,10.0),
                   'ba':(-1.0,1.0),'pa':(-1.0,1.0),'sky': (-8.0,8.0)},
            'absmag':{'mag':(-2.0,2.0),'absmag':(-2.0,2.0),
                      'rad':(-3.0,3.0),'n': (-8.0,8.0),
                    'BT':(-1.0,1.0),'rbulgerdisk':(-10.0,10.0),
                   'ba':(-1.0,1.0),'pa':(-1.0,1.0),'sky': (-8.0,8.0)},
            'rad':{'rad':(-1.0,1.0),'n': (-8.0,8.0),'sky': (-8.0,8.0)},
             'n':{'n':(-8.0,8.0)},
             'BT':{'mag':(-2.0,2.0),'rad':(-3.0,3.0),
                   'BT':(-1.0,1.0),'n':(-8.0,8.0),
                   'sky': (-8.0,8.0)},
             'pa':{'pa':(-1.0,1.0)},
             'ba':{'ba':(-1.0,1.0)},
             'rbulgerdisk':{'rbulgerdisk':(-10,10)}
            }

# selected by "ticks[x_tick][y_tick]"
ticksx = { 'mag':[1.0, 0.25,'%d'],'absmag':[2.0, 0.25,'%d'],
           'rad':[2.0, 0.5, '%d'],
           'n':[2.0, 0.5, '%02.1f'], 'BT':[0.2, 0.05,'%02.1f'],
           'ba':[0.2, 0.05,'%02.1f'],'pa':[60.0, 10.0,'%d'], 
           'rbulgerdisk':[0.5, 0.1, '%02.1f'], 'sky': [1.0,0.5, '%d']}

ticksy = {'mag':[0.2, 0.05,'%02.1f'],'absmag':[0.2, 0.05,'%02.1f'],
          'rad':[0.2, 0.05, '%02.1f'],
          'n':[2.0, 0.25, '%02.1f'], 'BT':[0.2, 0.05,'%02.1f'],
          'ba':[0.2, 0.05,'%02.1f'],'pa':[10.0, 5.0,'%d'], 
          'rbulgerdisk':[0.5, 0.1, '%02.1f'], 'sky':[1.0,0.25,'%d'],
          'sky_mag':[0.5, 0.1,'%02.1f'], 'sky_rad':[0.5, 0.1, '%02.1f'],
          'sky_rbulge':[1.0, 0.5, '%02.1f'],'sky_rdisk':[0.5, 0.1, '%02.1f'],
          'sky_n':[2.0, 0.5, '%02.1f'], 'sky_BT':[0.2, 0.05,'%02.1f'], 
          'sky_rbulgerdisk':[1.0, 0.2, '%02.1f'], 'sn':[20, 5,'%d'],
          'radfull':[2.0, 0.5, '%02.1f']}

xlabs = {'petromag':'m$_{\mathrm{petro,\ {band}}}$',
         'petromag_app':'m$_{\mathrm{petro,\ {band}}}$', 
         'petromag_abs':'M$_{\mathrm{petro,\ {band}}}$', 
         'mtot':'m$_{\mathrm{tot,\ {band},\ pm}}$',
         'mtot_app':'m$_{\mathrm{tot,\ {band},\ pm}}$', 
         'mtot_abs':'M$_{\mathrm{tot,\ {band},\ pm}}$', 
         'mbulge':'m$_{\mathrm{bulge,\ {band},\ pm}}$', 
         'pabulge':'$\phi_{\mathrm{bulge,\ {band},\ pm}}$', 
         'babulge':'(b/a)$_{\mathrm{bulge,\ {band},\ pm}}$', 
         'mdisk':'m$_{\mathrm{disk,\ {band},\ pm}}$',
         'padisk':'$\phi_{\mathrm{disk,\ {band},\ pm}}$', 
         'badisk':'(b/a)$_{\mathrm{disk,\ {band},\ pm}}$', 
         'hrad':'r$_{\mathrm{hl,\ {band},\ pm}}$ [arcsec]', 
         'hrad_corr':'r$_{\mathrm{hl,\ {band},\ pm}}$ [arcsec]', 
         'hrad_psf':'r$_{\mathrm{hl,\ {band},\ pm}}$ [arcsec]', 
         'batot':'(b/a)$_{\mathrm{tot,\ {band},\ pm}}$', 
         'rbulge':'r$_{\mathrm{bulge,\ {band},\ pm}}$ [arcsec]', 
         'rdisk':'r$_{\mathrm{disk,\ {band},\ pm}}$ [arcsec]',
         'n':'n$_{\mathrm{{band},\ pm}}$',
         'nbulge':'n$_{\mathrm{bulge,\ {band},\ pm}}$',
         'BT':'B/T$_{\mathrm{{band},\ pm}}$', 
         'rbulgerdisk': '(r$_{\mathrm{bulge,\ {band}}}\ $/$\ $r$_{\mathrm{disk,\ {band}}}$)$_{\mathrm{pm}}$',
         'cutsize': 'size', 
         'sky':r'$\Delta$sky$_{\mathrm{{band}}}$ (\%)'}

xlims = {'mtot':(14.0, 17.8),
         'mtot_app':(14.0, 17.8),
         'mtot_abs':(-25.0, -14.0),
         'petromag':(14.0, 17.8),
         'petromag_abs':(-25.0, -14.0),
         'mbulge':(15.0, 20.0) , 
         'mdisk':(15.0, 20.0),
         'hrad':(0.0, 10.0),
         'hrad_corr':(0.0, 10.0), 
         'petrorad':(0.0, 10.0), 
         'hrad_psf':(0.0, 10.0),
         'rbulge': (0.0, 10.0), 
         'rdisk':(0.0, 10.0),
         'n':(0.0, 8.0),
         'nbulge':(0.0, 8.0),
         'BT':(0.0, 1.0), 
         'babulge':(0.0, 1.0), 
         'badisk':(0.0, 1.0), 
         'batot':(0.0, 1.0), 
         'padisk':(0.0, 1.0), 
         'pabulge':(0.0, 360.0), 
         'rbulgerdisk':(0.0, 1.0),
         'cutsize': (8,27),
         'sky':(-2.0,2.0)}


ylabs = {'mtot':'$\Delta$m$_{\mathrm{tot,\ {band}}}$', 
         'mtot_abs':'$\Delta$M$_{\mathrm{tot,\ {band}}}$', 
         'mbulge':'$\Delta$m$_{\mathrm{bulge,\ {band}}}$', 
         'mdisk':'$\Delta$m$_{\mathrm{disk,\ {band}}}$',
         'hrad':'1 - (r/r$_{\mathrm{pm}})_{\mathrm{hl}}$', 
         'batot':'$\Delta$(b/a)$_{\mathrm{tot,\ {band}}}$', 
         'rbulge':'1 - (r/r$_{\mathrm{pm}})_{\mathrm{bulge}}$', 
         'rdisk':'1 - (r/r$_{\mathrm{pm}})_{\mathrm{disk}}$', 
         'pabulge':'$\Delta\phi_{\mathrm{bulge,\ {band}}}$', 
         'babulge':'$\Delta$(b/a)$_{\mathrm{bulge,\ {band}}}$', 
         'padisk':'$\Delta\phi_{\mathrm{disk,\ {band}}}$', 
         'badisk':'$\Delta$(b/a)$_{\mathrm{disk,\ {band}}}$', 
         'n':'$\Delta$n', 'BT':'$\Delta$B/T', 
         'nbulge':'$\Delta$n$_{bulge}$', 'BT':'$\Delta$B/T', 
         'rbulgerdisk': '$\Delta$(r$_{\mathrm{bulge,\ {band}}}\ $/$\ $r$_{\mathrm{disk,\ {band}}}$)',
         'sky':r'$\Delta$sky$_{\mathrm{{band}}}$ (\%)',
         'radfull':'r$_{\mathrm{hl,\ {band}}}$ [arcsec]'}

ylims = {'mtot':(-0.5, 0.5), 
         'mtot_abs':(-0.5, 0.5), 
         'mbulge':(-0.5, 0.5) , 
         'mdisk':(-0.5, 0.5),
         'hrad':(-0.5, 0.5), 
         'rbulge': (-0.5, 0.5), 
         'rdisk':(-0.5, 0.5),
         'babulge':(-0.2, 0.2), 
         'badisk':(-0.2, 0.2), 
         'batot':(-0.2, 0.2), 
         'padisk':(-20.0, 20.0), 
         'pabulge':(-20.0, 20.0), 
         'n':(-4.0, 4.0), 
         'nbulge':(-4.0, 6.0),
         'BT':(-0.5, 0.5), 
         'rbulgerdisk':(-0.5, 0.5), 
         'sky':(-1,1),
         'sky_mtot':(-1.2, 1.2), 
         'sky_mbulge':(-1.2, 1.2) , 
         'sky_mdisk':(-1.2, 1.2), 
         'sky_hrad':(-0.5, 0.5), 
         'sky_rbulge': (-4.0, 4.0), 
         'sky_rdisk':(-0.50, 0.50),
         'sky_n':(-3.0, 3.0), 
         'sky_BT':(-0.5, 0.5), 
         'sky_rbulgerdisk':(-1.5, 1.5),
         'sn': (0,60), 
         'rad':(0,15)}


def set_ticks(xch, ych):
    cur_tick = pub_plots(xmaj = ticksx[xch][0], xmin = ticksx[xch][1], 
                         xstr = ticksx[xch][2], ymaj = ticksy[ych][0], 
                         ymin = ticksy[ych][1], ystr = ticksy[ych][2])
    return cur_tick
        
ticks = { 'mag':{'mag':set_ticks('mag','mag'),
                 'radfull':set_ticks('mag','radfull'),
                 'rad':set_ticks('mag','rad'),
                 'n': set_ticks('mag','n'),
                 'BT':set_ticks('mag','BT'),
                 'ba':set_ticks('mag','ba'),
                 'pa':set_ticks('mag','pa'),
                 'rbulgerdisk':set_ticks('mag','rbulgerdisk'),
                 'sn':set_ticks('mag','sn'),
                 'sky':set_ticks('mag','sky')},
          'absmag':{'mag':set_ticks('mag','mag'),
                    'absmag':set_ticks('absmag','absmag'),
                 'radfull':set_ticks('mag','radfull'),
                 'rad':set_ticks('mag','rad'),
                 'n': set_ticks('mag','n'),
                 'BT':set_ticks('mag','BT'),
                 'ba':set_ticks('mag','ba'),
                 'pa':set_ticks('mag','pa'),
                 'rbulgerdisk':set_ticks('mag','rbulgerdisk'),
                 'sn':set_ticks('mag','sn'),
                 'sky':set_ticks('mag','sky')},
          'rad':{'rad':set_ticks('rad', 'rad'),
                 'sn':set_ticks('rad','sn'),
                 'n': set_ticks('rad','n'),
                 'sky':set_ticks('rad','sky')},
          'n':{'n':set_ticks('n', 'n')},
          'BT':{'BT':set_ticks('BT', 'BT'),
                'mag':set_ticks('BT', 'mag'),'n':set_ticks('BT', 'n'),
                'sky':set_ticks('BT','sky')},
          'ba':{'ba':set_ticks('ba', 'ba')},
          'pa':{'pa':set_ticks('pa', 'pa')},
          'rbulgerdisk':{'rbulgerdisk':set_ticks('rbulgerdisk', 'rbulgerdisk')},
          'sky':{'mag': set_ticks('sky', 'sky_mag'), 
                 'absmag': set_ticks('sky', 'sky_mag'), 
                 'rad': set_ticks('sky', 'sky_rad'),
                 'rbulge': set_ticks('sky', 'sky_rbulge'),
                 'rdisk': set_ticks('sky', 'sky_rdisk'),
                 'n':set_ticks('sky', 'sky_n'),
                 'BT': set_ticks('sky', 'sky_BT'),
                 'rbulgerdisk': set_ticks('sky', 'sky_rbulgerdisk')}
          }
