#!/bin/bash
#$ -t 1-1076
#$ -S /bin/bash
#$ -V
#$ -l h_vmem=2G
#$ -wd /data2/scratch/ameert/CMASS/i/fits/ser/
#$ -o /data2/scratch/ameert/CMASS/i/job_output/
#$ -e /data2/scratch/ameert/CMASS/i/job_output/
#$ -N hrad
#$ -tc 40


/data2/home/ameert/catalog/scripts/measure_and_clean2.py CMASS_i_ser $SGE_TASK_ID 


